repos:
  - repo: local
    hooks:
      - id: create-requirements-txt
        name: create-requirements-txt
        entry: poetry export -f requirements.txt --output requirements.txt --without-hashes
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: poetry run ruff leon_speedcams tests
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format leon_speedcams tests
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy leon_speedcams tests
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        always_run: true
        pass_filenames: false
